export type Cue='shot'|'reload'|'impact'|'damage'|'enemy'|'ui'|'slam';
export type FootstepSurface='grass'|'ground'|'wood'|'water';
const files={calm:'audio/calm.ogg',horde:'audio/horde.ogg',shot:'audio/shot.ogg',reload:'audio/reload.ogg',grass:'audio/footstep-grass.ogg',ground:'audio/footstep-ground.ogg'} as const;
type Sample=Exclude<keyof typeof files,'calm'|'horde'>;

/** Browser audio mixer. Recorded assets are preferred; procedural sounds remain as a resilient fallback. */
export class GameAudio {
  private context:AudioContext|null=null;private master:GainNode|null=null;private music:GainNode|null=null;private effects:GainNode|null=null;private calm:GainNode|null=null;private action:GainNode|null=null;private calmSource:AudioBufferSourceNode|null=null;private actionSource:AudioBufferSourceNode|null=null;private buffers=new Map<keyof typeof files,AudioBuffer>();private loading:Promise<void>|null=null;private stepTimer=0;private hordeMode=false;private bossMode=false;private effectWindow=0;private effectVoices=0;volume=.35;
  start(){try{this.context??=new AudioContext();if(!this.master){this.master=this.context.createGain();this.music=this.context.createGain();this.effects=this.context.createGain();this.calm=this.context.createGain();this.action=this.context.createGain();this.music.gain.value=.58;this.effects.gain.value=1;this.calm.gain.value=1;this.action.gain.value=0;this.calm.connect(this.music);this.action.connect(this.music);this.music.connect(this.master);this.effects.connect(this.master);this.master.connect(this.context.destination);}void this.context.resume();this.setVolume(this.volume);this.loading??=this.loadAssets();}catch{/* The game remains playable without Web Audio. */}}
  setVolume(v:number){this.volume=v;if(this.master&&this.context)this.master.gain.setTargetAtTime(v*.46,this.context.currentTime,.04);}
  pause(){void this.context?.suspend();}
  status(){return this.context?.state??'not-started';}
  cue(c:Cue){
    if(c==='shot'){if(!this.allowEffect())return;if(this.playSample('shot',1.3,.94+Math.random()*.1))return;this.noise(.085,.58,1500);this.tone(74,.15,'triangle',.44);return;}
    if(c==='reload'){if(this.playSample('reload',.9))return;this.noise(.035,.2,2800);this.tone(920,.045,'triangle',.28);return;}
    if(c==='slam'){if(!this.allowEffect())return;this.noise(.42,.5,190);this.tone(38,.5,'sawtooth',.62);return;}
    const notes:Record<Exclude<Cue,'shot'|'reload'|'slam'>,[number,number,OscillatorType,number]>={impact:[92,.07,'square',.24],damage:[54,.2,'sawtooth',.34],enemy:[72,.3,'triangle',.32],ui:[440,.08,'sine',.2]};const [f,d,t,v]=notes[c];this.tone(f,d,t,v);
  }
  update(dt:number,horde:boolean,speed=0,crouch=false,boss=false,surface:FootstepSurface='grass'){
    if(horde!==this.hordeMode||boss!==this.bossMode){this.hordeMode=horde;this.bossMode=boss;this.crossfade(horde);if(boss)this.cue('enemy');}
    this.stepTimer-=dt;if(speed>.45&&!crouch&&this.stepTimer<=0){this.stepTimer=speed>6?.27:.42;this.footstep(surface,speed>6);}
    if(speed<=.45)this.stepTimer=0;
  }
  private async loadAssets(){if(!this.context)return;await Promise.all((Object.keys(files) as (keyof typeof files)[]).map(async key=>{try{const response=await fetch(new URL(files[key],document.baseURI));if(!response.ok)throw new Error(String(response.status));this.buffers.set(key,await this.context!.decodeAudioData(await response.arrayBuffer()));}catch{/* Keep procedural fallback and gameplay available. */}}));this.startMusicLoops();}
  private startMusicLoops(){if(!this.context||!this.calm||!this.action||this.calmSource)return;const start=(key:'calm'|'horde',target:AudioNode)=>{const buffer=this.buffers.get(key);if(!buffer)return null;const source=this.context!.createBufferSource();source.buffer=buffer;source.loop=true;source.connect(target);source.start();return source;};this.calmSource=start('calm',this.calm);this.actionSource=start('horde',this.action);this.crossfade(this.hordeMode);}
  private crossfade(horde:boolean){if(!this.context||!this.calm||!this.action)return;const now=this.context.currentTime,fade=2.4;for(const [gain,target] of [[this.calm,horde?0:1],[this.action,horde?1:0]] as const){gain.gain.cancelScheduledValues(now);gain.gain.setValueAtTime(gain.gain.value,now);gain.gain.linearRampToValueAtTime(target,now+fade);}}
  private playSample(key:Sample,volume=1,rate=1){if(!this.context||!this.effects||this.context.state!=='running')return false;const buffer=this.buffers.get(key);if(!buffer)return false;const source=this.context.createBufferSource(),gain=this.context.createGain();source.buffer=buffer;source.playbackRate.value=rate;gain.gain.value=volume;source.connect(gain);gain.connect(this.effects);source.start();source.onended=()=>{source.disconnect();gain.disconnect();};return true;}
  private footstep(surface:FootstepSurface,run:boolean){const sample:Sample=surface==='grass'?'grass':'ground';if(this.playSample(sample,run?.38:.28,run?1.08:.94))return;this.noise(.045,run?.15:.1,run?520:420);this.tone(run?82:70,.055,'triangle',run?.14:.1);}
  private allowEffect(){if(!this.context||this.context.state!=='running')return false;const now=this.context.currentTime;if(now-this.effectWindow>.05){this.effectWindow=now;this.effectVoices=0;}return ++this.effectVoices<=6;}
  private noise(duration:number,volume:number,cutoff:number,delay=0,target:AudioNode|null=this.effects){if(!this.context||!target||this.context.state!=='running')return;const rate=this.context.sampleRate,size=Math.ceil(rate*duration),buffer=this.context.createBuffer(1,size,rate),data=buffer.getChannelData(0);for(let i=0;i<size;i++)data[i]=(Math.random()*2-1)*(1-i/size);const source=this.context.createBufferSource(),filter=this.context.createBiquadFilter(),gain=this.context.createGain(),time=this.context.currentTime+delay;source.buffer=buffer;filter.frequency.value=cutoff;gain.gain.setValueAtTime(volume,time);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);source.connect(filter);filter.connect(gain);gain.connect(target);source.start(time);source.stop(time+duration+.01);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
  private tone(frequency:number,duration:number,type:OscillatorType,volume:number,delay=0,endRatio=.6,target:AudioNode|null=this.effects){if(!this.context||!target||this.context.state!=='running')return;const time=this.context.currentTime+delay,oscillator=this.context.createOscillator(),gain=this.context.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,time);oscillator.frequency.exponentialRampToValueAtTime(Math.max(20,frequency*endRatio),time+duration);gain.gain.setValueAtTime(.0001,time);gain.gain.linearRampToValueAtTime(volume,time+.008);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);oscillator.connect(gain);gain.connect(target);oscillator.start(time);oscillator.stop(time+duration+.02);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}
}
