import * as T from 'three';
import { OutlineEffect } from 'three/addons/effects/OutlineEffect.js';
import { World } from '../world/World';
import { Avatar } from '../player/Avatar';
import { ThirdPerson } from '../camera/ThirdPerson';
import { Input } from '../input/Input';
import { TouchControls } from '../input/TouchControls';
import type { CombatAuthority } from './CombatAuthority';
import { Effects } from '../game/Effects';
import { GameAudio } from '../audio/Audio';
import { ClientPrediction } from './ClientPrediction';
import { AngleInterpolationBuffer, InterpolationBuffer, interpolationTick } from './Interpolation';
import { SnapshotTelemetry } from './SnapshotTelemetry';
import { SessionReport } from './SessionReport';
import { InputClock } from './InputClock';
import { ShotEventCursor } from './ShotEventCursor';
import { ReliablePlayerName } from './ReliablePlayerName';
import { resumeInputSequence } from './InputSequence';
import { ChatOutbox } from './Chat';
import { HealthEvents } from './HealthEvents';
import { controlsReady } from './ControlGate';
import { PredictedShotFeedback } from './PredictedShotFeedback';
import { CounterIncrease } from './CounterIncrease';
import { PhaseEvents } from './PhaseEvents';
import { SnapshotFreshness } from './SnapshotFreshness';
import { isPlayingPlayer, teamRoster } from './TeamRoster';
import { minimapPoint } from './Minimap';
import { TeamLifeEvents } from './TeamLifeEvents';
import { MAX_PLAYERS } from './MovementAuthority';
import { normalizeRoomCode, PUBLIC_ROOM_CODE, publicRoomInvite } from './RoomCode';
import { C, nextBoss } from '../config/gameplay';
type Snapshot=ReturnType<CombatAuthority['snapshot']>;
export function mountCoopPreview(app:HTMLElement){
  app.classList.add('coop-lobby');
  const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));const outline=new OutlineEffect(renderer,{defaultThickness:.006,defaultColor:[.06,.07,.06],defaultAlpha:1,defaultKeepAlive:true});app.append(renderer.domElement);
  const scene=new T.Scene();scene.background=new T.Color(0xf3f1e9);scene.fog=new T.Fog(0xf3f1e9,43,130);scene.add(new T.HemisphereLight(0xffffff,0xb4b7af,2.1));
  const light=new T.DirectionalLight(0xffffff,2.3);light.position.set(-20,35,10);scene.add(light);
  const world=new World(scene),camera=new ThirdPerson(),effects=new Effects(scene),audio=new GameAudio();
  const slamMaterial=new T.MeshBasicMaterial({color:0xb5211b,transparent:true,opacity:.5,side:T.DoubleSide,depthWrite:false});const slamMarker=new T.Mesh(new T.RingGeometry(.72,1,48),slamMaterial);slamMarker.rotation.x=-Math.PI/2;slamMarker.position.y=.035;slamMarker.visible=false;scene.add(slamMarker);
  const enemies=new Map<number,Avatar>(),labels=new Map<string,HTMLElement>(),playerBuffers=new Map<string,InterpolationBuffer>(),enemyBuffers=new Map<number,InterpolationBuffer>(),playerAngles=new Map<string,AngleInterpolationBuffer>(),enemyAngles=new Map<number,AngleInterpolationBuffer>(),shotEvents=new ShotEventCursor(),impactEvents=new ShotEventCursor();
  const crosshair=document.createElement('div');crosshair.className='coop-crosshair';crosshair.textContent='+';app.append(crosshair);
  const damageFlash=document.createElement('div');damageFlash.className='coop-damage-flash';app.append(damageFlash);
  const reward=document.createElement('div');reward.className='coop-reward';app.append(reward);
  const phaseBanner=document.createElement('div');phaseBanner.className='coop-phase-banner';app.append(phaseBanner);
  const teamAlert=document.createElement('div');teamAlert.className='coop-team-alert';app.append(teamAlert);
  const dayResult=document.createElement('div');dayResult.className='coop-day-result';dayResult.innerHTML='<small>DIA COMPLETO</small><b>DIA 1</b><dl><div><dt>INIMIGOS</dt><dd>0</dd></div><div><dt>DINHEIRO</dt><dd>$ 0</dd></div><div><dt>SOBREVIVENTES</dt><dd>0/0</dd></div></dl><span>PRÓXIMO CHEFÃO · DIA 10</span>';app.append(dayResult);
  const revive=document.createElement('div');revive.className='coop-revive';revive.hidden=true;revive.innerHTML='<b>VOCÊ CAIU</b><span>Modo de teste</span><button type="button">REVIVER AGORA</button>';app.append(revive);const reviveButton=revive.querySelector('button')!;
  const allyRevive=document.createElement('button');allyRevive.type='button';allyRevive.className='coop-ally-revive';allyRevive.hidden=true;app.append(allyRevive);let allyTarget='';
  const hud=document.createElement('div');hud.className='coop-hud';hud.innerHTML='<div class="coop-team" aria-label="Equipe"></div><div class="coop-minimap"><canvas width="180" height="180" aria-label="Minimapa"></canvas><small>VALE DO PAPEL</small></div><div class="coop-boss" hidden><b>O COLOSSO</b><i><em></em></i><span></span></div><div class="coop-day"><b>☼ &nbsp; DIA 1</b><span>PREPARAÇÃO · 00:40</span></div><div class="coop-stats"><b class="coop-money">$ 0</b><span class="coop-kills">✕ 0</span><small>CHEFÃO · DIA 10</small></div><div class="coop-protection" hidden>PROTEGIDO · 3s</div><div class="coop-health"><b>VOCÊ</b><span class="coop-hearts">♥ ♥ ♥</span><i><em></em></i><small>100 / 100</small></div><div class="coop-ammo"><small>PISTOLA</small><b>8 <span>/ 48</span></b><i></i></div>';app.append(hud);const protection=hud.querySelector<HTMLElement>('.coop-protection')!,team=hud.querySelector<HTMLElement>('.coop-team')!,minimap=hud.querySelector<HTMLCanvasElement>('.coop-minimap canvas')!,map=minimap.getContext('2d')!;
  const panel=document.createElement('div');panel.className='coop-panel';
  panel.innerHTML='<div class="coop-lobby-head"><span>SALA</span><strong>PAPEL</strong><button class="coop-invite" type="button">⧉ COPIAR CONVITE</button></div><p class="coop-lobby-status" role="status">Conectando…</p><div class="coop-lobby-list" aria-label="Participantes da sala"></div><div class="coop-lobby-actions"><label class="nickname">SEU NOME <input maxlength="16" autocomplete="nickname" placeholder="Como seus amigos verão você"></label><button class="join">ENTRAR NA PARTIDA</button><p class="help">Você fica protegido até entrar · até 8 jogadores</p><button class="coop-back" type="button">VOLTAR AO MENU</button></div><details><summary>DIAGNÓSTICO DE REDE</summary><output class="network-status">Aguardando primeiro estado…</output><button class="report">BAIXAR RELATÓRIO</button></details>';app.append(panel);
  const lobbyTitle=panel.querySelector('strong')!,status=panel.querySelector<HTMLElement>('.coop-lobby-status')!,networkStatus=panel.querySelector<HTMLOutputElement>('.network-status')!,button=panel.querySelector<HTMLButtonElement>('.join')!,inviteButton=panel.querySelector<HTMLButtonElement>('.coop-invite')!,backButton=panel.querySelector<HTMLButtonElement>('.coop-back')!,lobbyList=panel.querySelector<HTMLElement>('.coop-lobby-list')!,reportButton=panel.querySelector<HTMLButtonElement>('.report')!,help=panel.querySelector<HTMLElement>('.help')!,nickname=panel.querySelector<HTMLInputElement>('input')!,report=new SessionReport();nickname.value=localStorage.getItem('inkdays-nickname')??'';
  const chat=document.createElement('div');chat.className='coop-chat';chat.innerHTML='<div class="coop-chat-messages"></div><form hidden><input maxlength="100" aria-label="Mensagem para a equipe" autocomplete="off" enterkeyhint="send" placeholder="Digite uma mensagem…"><button type="button" aria-label="Fechar chat">×</button></form><small>ENTER · CHAT</small><button type="button" class="coop-chat-open" aria-label="Abrir chat">CHAT</button>';app.append(chat);const chatMessages=chat.querySelector<HTMLElement>('.coop-chat-messages')!,chatForm=chat.querySelector<HTMLFormElement>('form')!,chatInput=chat.querySelector<HTMLInputElement>('input')!,chatOpenButton=chat.querySelector<HTMLButtonElement>('.coop-chat-open')!,chatCloseButton=chat.querySelector<HTMLButtonElement>('form button')!,chatOutbox=new ChatOutbox();
  let id='',roomCode=PUBLIC_ROOM_CODE,snapshot:Snapshot|null=null,snapshotReceivedAt=0,sequence=0,last=0,connected=false,prediction:ClientPrediction|null=null,telemetry=new SnapshotTelemetry(),rtt=0,maxCorrection=0,snaps=0,round=0,lastReloading:boolean|null=null,lastSlamSerial=0;
  const avatars=new Map<string,Avatar>(),inputClock=new InputClock(),reliableName=new ReliablePlayerName(),healthEvents=new HealthEvents(),predictedShots=new PredictedShotFeedback(),moneyEvents=new CounterIncrease(),phaseEvents=new PhaseEvents(),teamLifeEvents=new TeamLifeEvents(),snapshotFreshness=new SnapshotFreshness();
  const pause=()=>{input.active=false;input.clear();touch.setActive(false);panel.classList.remove('playing');button.hidden=false;if(document.pointerLockElement)document.exitPointerLock();};
  const input=new Input(renderer.domElement,pause,()=>{}),touch=new TouchControls(input,pause,()=>{if(input.active)void renderer.domElement.requestPointerLock()?.catch(()=>{});});
  let socket:WebSocket,reconnectTimer=0,restartTimer=0,reviveTimer=0,allyReviveTimer=0,joinTimer=0,joinPending=false,pageLeaving=false,roomFull=false;
  const requestRestart=()=>{if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'restart'}));};
  inviteButton.onclick=async()=>{const invite=publicRoomInvite(location.href,roomCode);try{await navigator.clipboard.writeText(invite);inviteButton.textContent='✓ CONVITE COPIADO';}catch{inviteButton.textContent='COPIE O ENDEREÇO';}window.setTimeout(()=>inviteButton.textContent='⧉ COPIAR CONVITE',1800);};backButton.onclick=()=>{location.href=new URL('.',location.href).href;};
  const requestRevive=()=>{if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'revive'}));};reviveButton.onclick=()=>{requestRevive();clearInterval(reviveTimer);reviveTimer=window.setInterval(requestRevive,250);reviveButton.disabled=true;reviveButton.textContent='REVIVENDO…';};
  const requestAllyRevive=()=>{if(allyTarget&&socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'revive-ally',target:allyTarget}));};const startAllyRevive=()=>{if(!allyTarget||allyReviveTimer)return;requestAllyRevive();allyReviveTimer=window.setInterval(requestAllyRevive,250);allyRevive.textContent='AJUDANDO…';};allyRevive.onclick=startAllyRevive;
  const requestJoin=()=>{if(joinPending&&socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'ready'}));};const enterGameplay=()=>{joinPending=false;clearInterval(joinTimer);joinTimer=0;button.disabled=false;input.active=true;audio.start();app.classList.remove('coop-lobby');panel.classList.add('playing');button.hidden=true;nickname.parentElement!.hidden=true;help.hidden=true;if(!touch.enabled)void renderer.domElement.requestPointerLock()?.catch(()=>{status.textContent='Segure o botão direito para mirar.';});};
  button.onclick=()=>{if(!connected||joinPending)return;if(snapshot?.gameOver){requestRestart();clearInterval(restartTimer);restartTimer=window.setInterval(requestRestart,250);button.disabled=true;button.textContent='REINICIANDO…';return;}const name=reliableName.set(nickname.value);if(name)localStorage.setItem('inkdays-nickname',name);joinPending=true;button.disabled=true;button.textContent='ENTRANDO…';requestJoin();joinTimer=window.setInterval(requestJoin,250);};
  reportButton.onclick=()=>{const blob=new Blob([JSON.stringify(report.summary(),null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`inkdays-rede-${new Date().toISOString().replaceAll(':','-')}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};
  let chatOpen=false;const openChat=()=>{if(!input.active||chatOpen)return;chatOpen=true;input.clear();touch.setActive(false);chatForm.hidden=false;chatInput.focus();};
  const closeChat=()=>{chatOpen=false;chatForm.hidden=true;chatInput.blur();};chatOpenButton.onclick=openChat;chatCloseButton.onclick=closeChat;
  chatForm.onsubmit=e=>{e.preventDefault();if(chatOutbox.submit(chatInput.value)){chatInput.value='';closeChat();}};
  window.addEventListener('keydown',e=>{if(e.code==='KeyF'&&input.active&&!chatOpen&&allyTarget){e.preventDefault();startAllyRevive();}else if(e.code==='Enter'&&input.active&&!touch.enabled){if(!chatOpen){e.preventDefault();openChat();}else if(document.activeElement===chatInput){e.preventDefault();chatForm.requestSubmit();}}else if(e.code==='Escape'&&chatOpen){e.preventDefault();closeChat();}});
  const connect=()=>{
    const params=new URLSearchParams(location.search),requestedRoom=normalizeRoomCode(params.get('room')),token=sessionStorage.getItem(`inkdays-coop-token-${requestedRoom}`),override=params.get('server'),configured=import.meta.env.VITE_COOP_SERVER as string|undefined,url=new URL(override??configured??`${location.protocol==='https:'?'wss':'ws'}://${location.hostname}:8787`);url.searchParams.set('lobby','1');url.searchParams.set('room',requestedRoom);if(token)url.searchParams.set('resume',token);socket=new WebSocket(url);
    socket.onmessage=e=>{
    const packet=JSON.parse(e.data);
    if(packet.type==='room-full'){roomFull=true;connected=false;input.clear();status.textContent=`SALA CHEIA · ${packet.capacity??MAX_PLAYERS}/${packet.capacity??MAX_PLAYERS} JOGADORES`;button.disabled=true;button.textContent='SALA CHEIA';return;}
    if(packet.type==='pong'){const sample=performance.now()-packet.nonce;rtt=rtt?rtt*.8+sample*.2:sample;return;}
    if(packet.type==='welcome'){prediction=null;lastReloading=null;lastSlamSerial=0;slamMarker.visible=false;allyTarget='';clearInterval(allyReviveTimer);allyReviveTimer=0;allyRevive.hidden=true;input.clear();inputClock.advance(0,false);playerBuffers.clear();playerAngles.clear();enemyBuffers.clear();enemyAngles.clear();shotEvents.reset();impactEvents.reset();healthEvents.reset();predictedShots.reset();moneyEvents.reset();phaseEvents.reset();teamLifeEvents.reset();snapshotFreshness.reset();telemetry=new SnapshotTelemetry();rtt=0;if(packet.resumed)report.resumed();if(id&&id!==packet.id){report.newIdentity();prediction=null;sequence=0;maxCorrection=snaps=0;}id=packet.id;roomCode=normalizeRoomCode(packet.room);sessionStorage.setItem(`inkdays-coop-token-${roomCode}`,packet.token);connected=true;if(joinPending){requestJoin();joinTimer=window.setInterval(requestJoin,250);}status.textContent=packet.resumed?'Conexão recuperada. Aguardando estado…':'Conectado. Aguardando estado…';}
    if(packet.type==='snapshot'){
      const state=packet as Snapshot,receivedAt=performance.now(),unique=telemetry.observe(state.tick,receivedAt);if(!unique||state.tick<telemetry.latestTick)return;snapshotFreshness.observe(receivedAt);if(round&&state.round!==round){prediction=null;playerBuffers.clear();playerAngles.clear();enemyBuffers.clear();enemyAngles.clear();maxCorrection=snaps=0;}round=state.round;snapshot=state;snapshotReceivedAt=receivedAt;const me=state.players.find(p=>p.id===id);if(joinPending&&me&&me.ready!==false)enterGameplay();
      for(const event of teamLifeEvents.observe(state.players,id)){teamAlert.innerHTML=event.kind==='down'?`<b>${event.name} CAIU</b><span>APROXIME-SE PARA REVIVER</span>`:`<b>${event.name} VOLTOU</b><span>EQUIPE REUNIDA</span>`;teamAlert.classList.remove('visible','revived');void teamAlert.offsetWidth;if(event.kind==='revived')teamAlert.classList.add('revived');teamAlert.classList.add('visible');audio.cue('ui');}
      const announcement=phaseEvents.observe({round:state.round,day:state.day,phase:state.phase});if(announcement){const bossArrival=announcement.kind==='horde'&&state.boss;phaseBanner.innerHTML=bossArrival?`<small>CHEFÃO · DIA ${announcement.day}</small><b>${state.boss!.name}</b><span>PREPAREM-SE</span>`:announcement.kind==='horde'?`<b>HORDA</b><span>DIA ${announcement.day}</span>`:`<b>DIA ${announcement.day}</b><span>AMANHECEU</span>`;phaseBanner.classList.remove('visible','horde','boss');void phaseBanner.offsetWidth;if(announcement.kind==='horde')phaseBanner.classList.add('horde');if(bossArrival)phaseBanner.classList.add('boss');phaseBanner.classList.add('visible');audio.cue('ui');if(announcement.kind==='dawn'&&state.dayResult){dayResult.querySelector('b')!.textContent=`DIA ${state.dayResult.day}`;const values=dayResult.querySelectorAll('dd');values[0].textContent=String(state.dayResult.kills);values[1].textContent=`$ ${state.dayResult.money}`;values[2].textContent=`${state.dayResult.survivors}/${state.dayResult.players}`;dayResult.querySelector('span')!.textContent=`PRÓXIMO CHEFÃO · DIA ${state.dayResult.nextBoss}`;dayResult.classList.remove('visible');void dayResult.offsetWidth;dayResult.classList.add('visible');}}
      if(me){if(lastReloading===false&&me.reloading)audio.cue('reload');lastReloading=me.reloading;sequence=resumeInputSequence(sequence,me.acknowledged);reliableName.observe(me.name);chatOutbox.observe(me.chatAcknowledged);if(healthEvents.observe(me.health)>0){damageFlash.classList.remove('visible');void damageFlash.offsetWidth;damageFlash.classList.add('visible');}const gained=moneyEvents.observe(me.money);if(gained>0){reward.textContent=`+$${gained}`;reward.classList.remove('visible');void reward.offsetWidth;reward.classList.add('visible');}const authoritative={acknowledged:me.acknowledged,position:me.position,velocity:me.velocity,vertical:me.vertical};if(!prediction)prediction=new ClientPrediction(world,authoritative);else{const error=prediction.reconcile(authoritative);maxCorrection=Math.max(maxCorrection,error);if(error>3)snaps++;}}
      const seconds=Math.max(0,Math.ceil(state.remaining)),health=Math.max(0,me?.health??0),hearts=Math.ceil(health/(C.player.health/3));hud.querySelector('.coop-day b')!.textContent=`${state.phase==='horde'?'☾':'☼'}   DIA ${state.day}`;hud.querySelector('.coop-day span')!.textContent=`${state.phase==='horde'?'HORDA':'PREPARAÇÃO'} · ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;hud.querySelector('.coop-money')!.textContent=`$ ${me?.money??0}`;hud.querySelector('.coop-kills')!.textContent=`✕ ${me?.kills??0}`;hud.querySelector('.coop-stats small')!.textContent=`CHEFÃO · DIA ${nextBoss(state.day)}`;hud.querySelector('.coop-hearts')!.textContent=[0,1,2].map(index=>index<hearts?'♥':'♡').join(' ');(hud.querySelector('.coop-health em') as HTMLElement).style.width=`${health}%`;hud.querySelector('.coop-health small')!.textContent=`${Math.ceil(health)} / ${C.player.health}`;hud.querySelector('.coop-ammo b')!.innerHTML=`${me?.ammo??0} <span>/ ${me?.reserve??0}</span>`;hud.querySelector('.coop-ammo i')!.textContent=me?.reloading?'RECARREGANDO…':'';hud.classList.toggle('horde',state.phase==='horde');const bossHud=hud.querySelector<HTMLElement>('.coop-boss')!;bossHud.hidden=!state.boss;bossHud.classList.toggle('enraged',!!state.boss?.enraged);if(state.boss){bossHud.querySelector('b')!.textContent=`DIA ${state.day} — ${state.boss.name}${state.boss.enraged?' · FÚRIA':''}${state.boss.slam?' · IMPACTO':''}`;(bossHud.querySelector('em') as HTMLElement).style.width=`${Math.max(0,state.boss.health/state.boss.maxHealth*100)}%`;bossHud.querySelector('span')!.textContent=`${Math.ceil(state.boss.health)} / ${state.boss.maxHealth}`;}const slam=state.boss?.slam;slamMarker.visible=!!slam;if(slam){slamMarker.position.set(slam.position.x,.035,slam.position.z);slamMarker.scale.setScalar(slam.radius);if(slam.serial!==lastSlamSerial){lastSlamSerial=slam.serial;audio.cue('ui');}}
      team.replaceChildren(...teamRoster(state.players,id).map(entry=>{const row=document.createElement('div');row.className=`coop-team-player${entry.local?' local':''}${entry.down?' down':''}${entry.waiting?' waiting':''}${entry.connected?'':' offline'}`;const face=document.createElement('i'),info=document.createElement('span'),name=document.createElement('b'),track=document.createElement('em'),fill=document.createElement('u');face.textContent=entry.down?'×':entry.waiting?'○':'●';name.textContent=`${entry.local?`${entry.name} · VOCÊ`:entry.name}${entry.waiting?' · AGUARDANDO':''}`;fill.style.width=`${entry.healthPercent}%`;track.append(fill);info.append(name,track);row.append(face,info);return row;}));
      const activeCount=state.players.filter(isPlayingPlayer).length,connectedCount=state.players.filter(player=>player.connected).length;lobbyTitle.textContent=roomCode;status.textContent=`${connectedCount}/${MAX_PLAYERS} CONECTADOS · ${activeCount} NA PARTIDA · DIA ${state.day}`;lobbyList.replaceChildren(...Array.from({length:MAX_PLAYERS},(_,index)=>{const player=state.players[index],slot=document.createElement('span');if(player){const active=isPlayingPlayer(player);slot.className=active?'ready':'';const marker=document.createElement('i');marker.textContent=active?'●':'○';const info=document.createElement('span'),name=document.createElement('b');name.textContent=player.id===id?`${player.name} · VOCÊ`:player.name;const stateLabel=document.createElement('small');stateLabel.textContent=active?'NA PARTIDA':'AGUARDANDO';info.append(name,stateLabel);slot.append(marker,info);}else{slot.className='empty';slot.innerHTML='<i>＋</i><span>VAGA LIVRE</span>';}return slot;}));
      const mapSize=minimap.width;map.clearRect(0,0,mapSize,mapSize);map.save();map.beginPath();map.arc(mapSize/2,mapSize/2,mapSize*.46,0,Math.PI*2);map.clip();map.fillStyle='#f3f1e9';map.fillRect(0,0,mapSize,mapSize);map.strokeStyle='#7f857d';map.lineWidth=1;for(const offset of [-18,0,18]){map.beginPath();map.moveTo(15,mapSize/2+offset);map.quadraticCurveTo(mapSize/2,mapSize/2+offset*.25,mapSize-15,mapSize/2-offset*.35);map.stroke();}for(const enemy of state.enemies){const p=minimapPoint(enemy.position,C.world.radius,mapSize);map.beginPath();map.fillStyle=enemy.kind==='boss'?'#a30e13':'#cf493f';map.arc(p.x,p.y,enemy.kind==='boss'?5:2.4,0,Math.PI*2);map.fill();}for(const player of state.players.filter(isPlayingPlayer)){const p=minimapPoint(player.position,C.world.radius,mapSize);map.save();map.translate(p.x,p.y);map.rotate(player.yaw);map.beginPath();map.moveTo(0,-6);map.lineTo(4.5,5);map.lineTo(0,3);map.lineTo(-4.5,5);map.closePath();map.fillStyle=player.id===id?'#171918':'#687e9b';map.fill();map.restore();}map.restore();map.strokeStyle='#171918';map.lineWidth=4;map.beginPath();map.arc(mapSize/2,mapSize/2,mapSize*.46,0,Math.PI*2);map.stroke();
      protection.hidden=!me||me.protection<=0;protection.textContent=`PROTEGIDO · ${Math.ceil(me?.protection??0)}s`;revive.hidden=me?.health!==0;if(me?.health!==0&&reviveTimer){clearInterval(reviveTimer);reviveTimer=0;reviveButton.disabled=false;reviveButton.textContent='REVIVER AGORA';}const downed=me&&me.health>0?state.players.filter(player=>player.id!==id&&player.connected&&player.health===0).map(player=>({player,distance:Math.hypot(player.position.x-me.position.x,player.position.z-me.position.z)})).filter(entry=>entry.distance<=C.player.reviveRange).sort((a,b)=>a.distance-b.distance)[0]:undefined,nextAllyTarget=downed?.player.id??'';if(allyReviveTimer&&nextAllyTarget!==allyTarget){clearInterval(allyReviveTimer);allyReviveTimer=0;}allyTarget=nextAllyTarget;allyRevive.hidden=!downed;allyRevive.textContent=downed?(allyReviveTimer?'AJUDANDO…':`${touch.enabled?'REVIVER':'F · REVIVER'} ${downed.player.name}`):'';
      networkStatus.textContent=`DIA ${state.day} · ${state.phase==='horde'?'HORDA':'PREPARAÇÃO'} ${Math.ceil(state.remaining)}s · Vida ${me?.health??0} · ${me?.ammo??0}/${me?.reserve??0} · $${me?.money??0} · ping ${rtt.toFixed(0)}ms · jitter ${telemetry.jitter.toFixed(0)}ms · perda ${telemetry.lossPercent.toFixed(0)}% · correção máx. ${(maxCorrection*100).toFixed(0)}cm · saltos ${snaps}${state.gameOver?' · FIM DE PARTIDA':me?.health===0?' · VOCÊ MORREU':''}`;
      if(!state.gameOver&&restartTimer){clearInterval(restartTimer);restartTimer=0;}button.disabled=joinPending||state.gameOver&&!!restartTimer;button.textContent=joinPending?'ENTRANDO…':restartTimer?'REINICIANDO…':state.gameOver?'JOGAR NOVAMENTE':me?.ready===false?'ENTRAR NA PARTIDA':'CONTINUAR';
      report.sample({day:state.day,tick:state.tick,rtt,jitter:telemetry.jitter,loss:telemetry.lossPercent,correction:maxCorrection,snaps,rewindTicks:Math.max(0,...state.shots.map(shot=>shot.rewindTicks))});
      const playingPlayers=(packet as Snapshot).players.filter(isPlayingPlayer),ids=new Set(playingPlayers.map(p=>p.id));
      for(const [key,avatar] of avatars)if(!ids.has(key)){scene.remove(avatar.root);avatars.delete(key);playerBuffers.delete(key);playerAngles.delete(key);labels.get(key)?.remove();labels.delete(key);}
      for(const player of playingPlayers)if(!avatars.has(player.id)){const avatar=new Avatar();avatar.root.position.copy(player.position);avatars.set(player.id,avatar);scene.add(avatar.root);}
      for(const player of playingPlayers)if(player.id!==id){let buffer=playerBuffers.get(player.id),angle=playerAngles.get(player.id);if(!buffer){buffer=new InterpolationBuffer();playerBuffers.set(player.id,buffer);}if(!angle){angle=new AngleInterpolationBuffer();playerAngles.set(player.id,angle);}buffer.push(state.tick,player.position,receivedAt);angle.push(state.tick,player.yaw+Math.PI,receivedAt);}
      for(const player of playingPlayers)if(player.id!==id&&!labels.has(player.id)){const label=document.createElement('span');label.textContent=player.name;Object.assign(label.style,{position:'fixed',color:'#171918',fontWeight:'800',fontSize:'11px',textShadow:'0 1px #f3f1e9,1px 0 #f3f1e9,0 -1px #f3f1e9,-1px 0 #f3f1e9',pointerEvents:'none',transform:'translate(-50%,-100%)'});app.append(label);labels.set(player.id,label);}
      for(const player of playingPlayers)if(player.id!==id){const label=labels.get(player.id);if(label){label.textContent=!player.connected?`${player.name} · reconectando`:player.health===0?`${player.name} · CAÍDO`:player.name;label.style.opacity=player.connected?'1':'.5';label.style.color=player.health===0?'#a62821':'#171918';}}
      const enemyIds=new Set(state.enemies.map(e=>e.id));for(const [key,avatar] of enemies)if(!enemyIds.has(key)){scene.remove(avatar.root);enemies.delete(key);enemyBuffers.delete(key);enemyAngles.delete(key);}
      for(const enemy of state.enemies)if(!enemies.has(enemy.id)){const avatar=new Avatar(true,enemy.kind==='boss');avatar.root.position.copy(enemy.position);if(enemy.kind==='boss')avatar.root.scale.setScalar(C.boss.scale);enemies.set(enemy.id,avatar);scene.add(avatar.root);}
      for(const enemy of state.enemies){let buffer=enemyBuffers.get(enemy.id),angle=enemyAngles.get(enemy.id);if(!buffer){buffer=new InterpolationBuffer();enemyBuffers.set(enemy.id,buffer);}if(!angle){angle=new AngleInterpolationBuffer();enemyAngles.set(enemy.id,angle);}buffer.push(state.tick,enemy.position,receivedAt);angle.push(state.tick,enemy.yaw,receivedAt);}
      for(const shot of shotEvents.consume(state.shots)){effects.shot(new T.Vector3().copy(shot.from),new T.Vector3().copy(shot.to));if(shot.hit){effects.impact(new T.Vector3().copy(shot.to));if(shot.player===id){crosshair.classList.remove('hit');void crosshair.offsetWidth;crosshair.classList.add('hit');}}if(shot.player!==id||!predictedShots.confirm(shot.shotId,receivedAt))audio.cue('shot');}
      for(const impact of impactEvents.consume(state.impacts)){const point=new T.Vector3().copy(impact.position);effects.slam(point,impact.radius);audio.cue('slam');const local=avatars.get(id)?.root.position;if(local){const distance=local.distanceTo(point);camera.shake=Math.max(camera.shake,Math.max(0,.7-distance/(impact.radius*2)*.55));}}
      chatMessages.replaceChildren(...(state.messages??[]).slice(-3).map(message=>{const line=document.createElement('div'),name=document.createElement('b');name.textContent=`${message.name}: `;line.append(name,document.createTextNode(message.text));return line;}));
      if(me?.health===0&&input.active)pause();
    }
    };
    socket.onclose=e=>{connected=false;clearInterval(joinTimer);joinTimer=0;button.disabled=false;if(joinPending)button.textContent='RECONECTANDO…';allyTarget='';clearInterval(allyReviveTimer);allyReviveTimer=0;allyRevive.hidden=true;input.clear();if(!pageLeaving&&!roomFull)report.disconnected();if(roomFull)return;status.textContent=e.reason||'Reconectando…';if(!pageLeaving)reconnectTimer=window.setTimeout(connect,1000);};
    socket.onerror=()=>{status.textContent='Conexão interrompida. Tentando recuperar…';};
  };
  connect();
  const pingTimer=window.setInterval(()=>{if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'ping',nonce:performance.now()}));},2000);
  window.addEventListener('pagehide',()=>{pageLeaving=true;clearTimeout(reconnectTimer);clearInterval(restartTimer);clearInterval(reviveTimer);clearInterval(allyReviveTimer);clearInterval(joinTimer);clearInterval(pingTimer);socket.close();});
  window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
  const resize=()=>{outline.setSize(innerWidth,innerHeight);camera.camera.aspect=innerWidth/innerHeight;camera.camera.updateProjectionMatrix();};window.addEventListener('resize',resize);resize();
  function frame(now:number){
    requestAnimationFrame(frame);const dt=Math.min(.1,(now-(last||now))/1000);last=now;if(connected&&snapshotFreshness.stale(now)){connected=false;input.clear();status.textContent='Estado desatualizado. Reconectando…';socket.close(4000,'Estado autoritativo expirou');}
    const namePacket=connected&&socket.readyState===WebSocket.OPEN?reliableName.packet(now):null;if(namePacket)socket.send(JSON.stringify(namePacket));const chatPacket=connected&&socket.readyState===WebSocket.OPEN?chatOutbox.packet(now):null;if(chatPacket)socket.send(JSON.stringify(chatPacket));
    const ready=controlsReady(input.active,connected&&socket.readyState===WebSocket.OPEN,prediction!==null,chatOpen);if(ready)camera.look(input.lookX,input.lookY,1);input.lookX=input.lookY=0;touch.setActive(ready&&innerWidth>innerHeight);
    const steps=inputClock.advance(dt,ready);
    for(let step=0;step<steps&&prediction;step++){
      const sent=sequence++,raw=input.consume(),command=prediction.prepare(sent,raw);if(raw.shot&&prediction.shotId!==undefined){audio.cue('shot');predictedShots.predict(prediction.shotId,now);}const yaw=Math.atan2(Math.sin(camera.yaw),Math.cos(camera.yaw)),viewTick=Math.max(0,Math.floor(interpolationTick(snapshot?.tick??6,snapshotReceivedAt||now,now)));prediction.submit({sequence:sent,yaw,command});socket.send(JSON.stringify({version:1,sequence:sent,yaw,pitch:camera.pitch,viewTick,shotId:prediction.shotId,command}));
    }
    if(snapshot)for(const player of snapshot.players.filter(isPlayingPlayer)){
      const avatar=avatars.get(player.id)!;if(player.id===id&&prediction){prediction.updateRender(dt);avatar.root.position.copy(prediction.renderPosition);avatar.root.rotation.y=player.yaw+Math.PI;}else{const sampled=playerBuffers.get(player.id)?.sample(now),angle=playerAngles.get(player.id)?.sample(now);if(sampled)avatar.root.position.copy(sampled);if(angle!==null&&angle!==undefined)avatar.root.rotation.y=angle;}avatar.animate(now/1000,Math.hypot(player.velocity.x,player.velocity.z),player.crouch,false,player.velocity);avatar.body.rotation.z=player.health===0?1.5:0;
    }
    if(snapshot)for(const enemy of snapshot.enemies){const avatar=enemies.get(enemy.id)!,sampled=enemyBuffers.get(enemy.id)?.sample(now),angle=enemyAngles.get(enemy.id)?.sample(now);if(sampled)avatar.root.position.copy(sampled);if(angle!==null&&angle!==undefined)avatar.root.rotation.y=angle;if(enemy.kind==='boss')avatar.root.scale.setScalar(C.boss.scale*(enemy.enraged?1.03+Math.sin(now*.012)*.025:1));avatar.animate(now/1000,enemy.state==='CHASE'?enemy.speed:0,false,enemy.state==='ATTACK');}
    camera.update(dt,avatars.get(id)?.root.position??new T.Vector3(0,0,10),world,true);
    for(const [key,label] of labels){const point=avatars.get(key)!.root.position.clone().add(new T.Vector3(0,2.5,0)).project(camera.camera);label.hidden=point.z>1||point.z< -1;label.style.left=`${(point.x+1)*innerWidth/2}px`;label.style.top=`${(1-point.y)*innerHeight/2}px`;}
    effects.update(dt);if(connected&&snapshot){const me=snapshot.players.find(player=>player.id===id),slam=snapshot.boss?.slam;if(slam){const urgency=1-T.MathUtils.clamp(slam.remaining/C.boss.slamWindup,0,1);slamMaterial.opacity=.25+urgency*.6;slamMarker.rotation.z=now*.0015;slamMarker.scale.setScalar(slam.radius*(.94+Math.sin(now*.018)*.035));}audio.update(dt,snapshot.phase==='horde',me?Math.hypot(me.velocity.x,me.velocity.z):0,me?.crouch??false,!!snapshot.boss);(scene.background as T.Color).lerp(new T.Color(snapshot.phase==='horde'?0x737b78:0xf3f1e9),dt*1.35);(scene.fog as T.Fog).color.copy(scene.background as T.Color);light.intensity=T.MathUtils.damp(light.intensity,snapshot.phase==='horde'?.85:2.3,1.8,dt);}outline.render(scene,camera.camera);
  }
  requestAnimationFrame(frame);
}
