export interface NetworkSample {day:number;tick:number;rtt:number;jitter:number;loss:number;correction:number;snaps:number}
export interface SessionSummary {startedAt:string;durationSeconds:number;samples:number;lastDay:number;lastTick:number;averagePingMs:number;maximumPingMs:number;averageJitterMs:number;maximumJitterMs:number;averageLossPercent:number;maximumLossPercent:number;maximumCorrectionCm:number;hardCorrections:number;disconnects:number;resumes:number;newIdentities:number}
/** Small aggregate-only QA recorder; it stores no player identity or chat content. */
export class SessionReport {
  private started=Date.now();private count=0;private totals={rtt:0,jitter:0,loss:0};private maximum={rtt:0,jitter:0,loss:0,correction:0};private last={day:1,tick:0,snaps:0};private disconnectCount=0;private resumeCount=0;private identityCount=0;
  sample(value:NetworkSample){this.count++;this.last={day:value.day,tick:value.tick,snaps:value.snaps};this.totals.rtt+=value.rtt;this.totals.jitter+=value.jitter;this.totals.loss+=value.loss;this.maximum.rtt=Math.max(this.maximum.rtt,value.rtt);this.maximum.jitter=Math.max(this.maximum.jitter,value.jitter);this.maximum.loss=Math.max(this.maximum.loss,value.loss);this.maximum.correction=Math.max(this.maximum.correction,value.correction);}
  disconnected(){this.disconnectCount++;} resumed(){this.resumeCount++;} newIdentity(){this.identityCount++;}
  summary(now=Date.now()):SessionSummary {const divisor=this.count||1;return {startedAt:new Date(this.started).toISOString(),durationSeconds:Math.max(0,(now-this.started)/1000),samples:this.count,lastDay:this.last.day,lastTick:this.last.tick,averagePingMs:this.totals.rtt/divisor,maximumPingMs:this.maximum.rtt,averageJitterMs:this.totals.jitter/divisor,maximumJitterMs:this.maximum.jitter,averageLossPercent:this.totals.loss/divisor,maximumLossPercent:this.maximum.loss,maximumCorrectionCm:this.maximum.correction*100,hardCorrections:this.last.snaps,disconnects:this.disconnectCount,resumes:this.resumeCount,newIdentities:this.identityCount};}
}
